version: 2

models:
  - name: stg_customers
    description: "Cleaned customers staging model"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_orders
    description: "Cleaned orders staging model with calculation"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique